analyze_image:
  stage: analyze
  image:
    name: trivoallan/regis-cli:latest
    entrypoint: [""]
  before_script:
    - mkdir -p public
  script:
    - |
      regis-cli analyze "$IMAGE_URL" \
        --site \
        --output-dir public \
        --meta "trigger.user=$GITLAB_USER_LOGIN" \
        --meta "trigger.url=$CI_JOB_URL"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
