"""Tests for render_html_single in regis.report.html."""

from regis.report.html import render_html_single


def _minimal_report(**extra) -> dict:
    base = {
        "request": {
            "registry": "registry-1.docker.io",
            "repository": "library/nginx",
            "tag": "latest",
            "timestamp": "2026-04-25T10:00:00+00:00",
        },
        "results": {},
        "playbooks": [],
    }
    base.update(extra)
    return base


class TestRenderHtmlSingle:
    def test_returns_string(self):
        html = render_html_single(_minimal_report())
        assert isinstance(html, str)

    def test_contains_doctype(self):
        html = render_html_single(_minimal_report())
        assert "<!DOCTYPE html>" in html

    def test_contains_image_ref_in_title(self):
        html = render_html_single(_minimal_report())
        assert "registry-1.docker.io/library/nginx:latest" in html

    def test_no_external_resources(self):
        html = render_html_single(_minimal_report())
        # Must not reference external URLs in link/script/img tags
        assert 'href="http' not in html
        assert 'src="http' not in html
        assert "href='http" not in html
        assert "src='http" not in html

    def test_no_javascript(self):
        html = render_html_single(_minimal_report())
        assert "<script" not in html

    def test_playbook_table_present_when_playbooks(self):
        report = _minimal_report(
            playbooks=[
                {
                    "name": "default",
                    "verdict": "PASS",
                    "score": 95,
                    "rules": [{"passed": True}, {"passed": True}],
                }
            ]
        )
        html = render_html_single(report)
        assert "default" in html
        assert "PASS" in html

    def test_playbook_table_absent_when_no_playbooks(self):
        html = render_html_single(_minimal_report())
        assert "Playbook results" not in html

    def test_snapshot_date_shown_when_present(self):
        html = render_html_single(_minimal_report(snapshot_date="2026-04-09"))
        assert "2026-04-09" in html

    def test_snapshot_date_absent_when_missing(self):
        html = render_html_single(_minimal_report())
        assert "Snapshot date" not in html

    def test_sections_all_includes_analyzer(self):
        report = _minimal_report(results={"trivy": {"score": 80, "cves": []}})
        html = render_html_single(report, sections="all")
        assert "trivy" in html

    def test_sections_summary_excludes_detail_tables(self):
        report = _minimal_report(
            results={
                "trivy": {
                    "score": 80,
                    "vulnerabilities": [
                        {"id": "CVE-2023-1234", "severity": "CRITICAL"}
                    ],
                }
            }
        )
        html = render_html_single(report, sections="summary")
        # score scalar shown, but CVE table detail not shown
        assert "trivy" in html
        assert "80" in html  # scalar score should be visible in summary
        assert "CVE-2023-1234" not in html

    def test_sections_filter_by_slug(self):
        report = _minimal_report(
            results={"trivy": {"score": 80}, "hadolint": {"warnings": 3}}
        )
        html = render_html_single(report, sections="trivy")
        assert "trivy" in html
        assert "hadolint" not in html

    def test_unknown_slug_does_not_raise(self):
        report = _minimal_report(results={"trivy": {"score": 80}})
        html = render_html_single(report, sections="unknown_analyzer")
        assert isinstance(html, str)

    def test_unknown_slug_warns_to_stderr(self, capsys):
        report = _minimal_report(results={"trivy": {"score": 80}})
        render_html_single(report, sections="unknown_analyzer")
        captured = capsys.readouterr()
        assert "unknown_analyzer" in captured.err

    def test_sections_defaults_to_all(self):
        report = _minimal_report(results={"trivy": {"score": 80}})
        html_default = render_html_single(report)
        html_explicit = render_html_single(report, sections="all")
        assert html_default == html_explicit

    def test_footer_contains_generated_by(self):
        html = render_html_single(_minimal_report())
        assert "Generated by regis" in html
