name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        id: pr-preview
        with:
          source-dir: .
          preview-branch: main
          umbrella-dir: incoming
          qr-code: false
          comment: false
          wait-for-pages-deployment: true

      - name: Split branch name
        env:
          BRANCH: "{% raw %}${{ github.head_ref }}{% endraw %}"
        id: split
        run: echo "fragment=${BRANCH##*/}" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: "{% raw %}${{ github.event.pull_request.number }}{% endraw %}"
          body: |
            Browse the [RegiS Report](https://trivoallan.github.io/regis/dashboard/report/?url={% raw %}${{ steps.pr-preview.outputs.preview-url }}${{ steps.split.outputs.fragment }}{% endraw %}/report.json)

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: main
          umbrella-dir: incoming
          action: remove
