import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";

const config: Config = {
  title: "regis-cli Report",
  tagline: "Container Security Analysis Report",
  favicon: "img/favicon.ico",

  // These are overridden at build time via env vars
  url: process.env.REPORT_URL || "http://localhost",
  baseUrl: process.env.REPORT_BASE_URL || "/",

  onBrokenLinks: "warn",

  markdown: {
    format: "detect",
    mermaid: true,
  },

  future: {
    v4: false,
  },

  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  themes: ["@docusaurus/theme-mermaid"],

  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarItemsGenerator: async () => {
            // Custom sidebar: fixed structure matching the report
            return [
              { type: "doc", id: "index", label: "Overview" },
              { type: "doc", id: "rules", label: "Rules" },
              { type: "doc", id: "playbook", label: "Playbook" },
            ];
          },
        },
        blog: false,
        pages: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: "dark",
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "Report",
      items: [
        {
          href: "/report.json",
          label: "Raw JSON",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      copyright: `Generated by <a href="https://github.com/trivoallan/regis-cli">regis-cli</a>`,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
