name: Trunk Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trunk Fmt
        run: npx trunk fmt --all

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
