name: Repo / Auto-merge

on:
  pull_request_target:
    types: [opened, ready_for_review]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  automerge:
    if: >-
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.REGIS_CI_APP_ID }}
          private-key: ${{ secrets.REGIS_CI_APP_PRIVATE_KEY }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
