name: Trunk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      statuses: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trunk Install
        uses: trunk-io/trunk-action/setup@v1

      - name: Trunk Format
        run: ${{ env.TRUNK_PATH }} fmt --all

      - name: Commit and Push Changes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref }}
          commit_message: "style(cli): apply automated trunk fmt"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
